<div class="block block-list block-compare">
    <div class="block-title">
        <strong><span><?php echo $this->__('New Products RSS Feed') ?>
        </span></strong>
    </div>
    <div class="block-content">
<?php
    $_new = $this->getRssNewFeeds();
?>
<?php if ($_new): ?>
<table class="data-table rss-table" id="rss-table-misc">
    <col />
    <col width="1" />
    <tbody>
        <?php foreach ($_new as $_feed): ?>
        <tr>
            <td><?php echo $_feed->getLabel() ?></td>
            <td><a href="<?php echo $_feed->getUrl() ?>" class="link-rss"><?php echo $this->__('RSS'); ?></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
//<![CDATA[
    decorateTable('rss-table-misc');
//]]>
</script>
<?php else: ?>
    <p><?php echo $this->__('There are no Rss Feeds'); ?></p>
<?php endif; ?>
    </div>
</div>